{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "scylla-operator.certificateName" . }}
  creationTimestamp: null
  name: scylla-operator-mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "scylla-operator.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-scylla-scylladb-com-v1-scyllacluster
  admissionReviewVersions:
  - v1
  sideEffects: None
  failurePolicy: Fail
  name: webhook.scylla.scylladb.com
  rules:
  - apiGroups:
    - scylla.scylladb.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - scyllaclusters
{{- end }}
